// <auto-generated />
namespace BGale_WEBD3000_MyTunes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReleaseDateToAlbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReleaseDateToAlbum));
        
        string IMigrationMetadata.Id
        {
            get { return "201603280210008_AddReleaseDateToAlbum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
