// <auto-generated />
namespace BGale_WEBD3000_MyTunes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddRowVersionToRemaining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRowVersionToRemaining));
        
        string IMigrationMetadata.Id
        {
            get { return "201604030312391_AddRowVersionToRemaining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
